// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI_Lc3GqPZUDDQxGpBn1wb3Rx3zaKMdHo',
    appId: '1:32991462466:web:0d4290cbddb8a3666219db',
    messagingSenderId: '32991462466',
    projectId: 'flutterbloctest-bd126',
    authDomain: 'flutterbloctest-bd126.firebaseapp.com',
    storageBucket: 'flutterbloctest-bd126.appspot.com',
    measurementId: 'G-RDRB2EPV9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB43rZoipR2sLUM00SZzN7h2nVfcO3Rlw',
    appId: '1:32991462466:android:ab5a6e58010393296219db',
    messagingSenderId: '32991462466',
    projectId: 'flutterbloctest-bd126',
    storageBucket: 'flutterbloctest-bd126.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYGEknT3kzsjVp6lpQhQ36RDXTclSDT-E',
    appId: '1:32991462466:ios:1b80593a07858ee96219db',
    messagingSenderId: '32991462466',
    projectId: 'flutterbloctest-bd126',
    storageBucket: 'flutterbloctest-bd126.appspot.com',
    iosClientId: '32991462466-ss08fgesdrcv8k9ccpnj64q763jrao7m.apps.googleusercontent.com',
    iosBundleId: 'com.aaaa.app',
  );
}
